### ISSUE TITLE
Corrupt rdb

### ISSUE THREAD

**Issue by neilhatfield** [EducationShinyAppTeam/boastUtils#21]
Getting the following error on autocomplete of calls from boastUtils:

```
Error in fetch(key) : 
  lazy-load database '/Library/Frameworks/R.framework/Versions/4.0/Resources/library/boastUtils/help/boastUtils.rdb' is corrupt
```

**Comment by rpc5102** [comment]
See: https://github.com/r-lib/devtools/issues/942#issuecomment-144390231

**Comment by neilhatfield** [comment]
Did a restart and will keep an eye on it to see if it comes back.

**Comment by neilhatfield** [comment]
No new issues.
